### ISSUE TITLE
Logging in with Google in Chrome spawns "He's Dead, Jim"

### ISSUE THREAD

**Issue by nap7276** [Mottokrosh/SheetIssues#21]
First encountered this error tonight on most recent Chrome in Linux Mint and Windows 7. If I log in with Google authentication, it will seem to accept the login, briefly show the screen displaying the "Active Characters", "New Character" and "Archived Characters" buttons then quickly switch to the "He's Dead, Jim!" error page, saying the process has run out of memory or been terminated.

If I refresh the same tab, the same error page appears. If I open another tab and go to charactersheet.co.uk in that tab, I'm already logged in and it works. This error does not happen in Mozilla Firefox. I have not tried to reproduce the error in any other browsers or by using the Github login.

**Comment by Mottokrosh** [comment]
This should now be fixed!
