### ISSUE TITLE
Chrome Crash

### ISSUE THREAD

**Issue by irvanovich** [Mottokrosh/SheetIssues#23]
Latest version of Chrome gives an "Aw, snap" error when trying to load character sheets. Reproduced error on Win8 laptop and Android smartphone. Will load on Explorer and Firefox just fine.

**Comment by Mottokrosh** [comment]
Wow, that's bad. Just reproduced it myself. No code changes on my end, so I wonder what Chrome has done this time! Ideas welcome.

**Comment by niertis** [comment]
After providing my login and get the "Aw, snap" page, I remove "/#/login" from the url and try again and it works. Not sure if Chrome is having a path issue there.

**Comment by irvanovich** [comment]
I'll try that when I get home. Thanks!

**Comment by irvanovich** [comment]
Correction, I'll try it on my mobile now...removing the /#/login from the
url, it worked just fine. Will confirm from my home pc in a couple of hours
:)

**Comment by Mottokrosh** [comment]
Thanks guys, this all helps.

**Comment by GilesPenfold** [comment]
Hi guys, I've been getting this the past few weeks also. Tried removing the /#/login but no avail. Seems to work fine in Firefox though. Silly Chrome.

**Comment by Mottokrosh** [comment]
I have finally deployed a workaround for this issue, which should fix the Chrome crash!

I've tested it on several devices successfully, but let me know if your mileage varies.

Sorry this took so long, but honestly I've not been able to figure out the exact cause for the crash, but I managed to put a workaround in place that bypasses it.
