### ISSUE TITLE
Consider Open sourcing.

### ISSUE THREAD

**Issue by zarthross** [Mottokrosh/SheetIssues#28]
Have you considered open sourcing this so others might improve upon what you've done?

**Comment by Mottokrosh** [comment]
Absolutely: https://github.com/Mottokrosh/SheetIssues/issues/15

I just need that little bit of time to get the ball rolling...

**Comment by g-r-u** [comment]
I fully agree with this route.  Open source for self-hosting, along with a subscription-based cloud hosting service would be an excellent way to present this app.  I'd pay for the cloud hosting option, for sure.

**Comment by Mottokrosh** [comment]
This repo is deprecated. Please use the official - long open sourced :) - one: https://github.com/Mottokrosh/Sheet
