### ISSUE TITLE
Cant find how to make character active.

### ISSUE THREAD

**Issue by jesse1125** [Mottokrosh/SheetIssues#29]
I build a character but can't find how to save it or make it active so I don't have to fill out all the info again.

**Comment by Mottokrosh** [comment]
Hi Jesse,

Characters are automatically saved whenever you enter anything or make a change. Your characters are listed on the homepage (where you can load them with the "Edit"button).

**Comment by jesse1125** [comment]
Yes I understand that but only 1 of 2 character sheets shows up that I have created and the one that does load just has character name and player name filled in all other states adjustments I did, did not save.
